/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author amagu
 */
public class ConsultaCatalogo extends javax.swing.JPanel {

    /**
     * Creates new form ConsultaCatalogo
     */
    public ConsultaCatalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jtxt_buscarLibros = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        libro1Panel = new javax.swing.JPanel();
        lblTitulo1 = new javax.swing.JLabel();
        lblAutor1 = new javax.swing.JLabel();
        lblGenero1 = new javax.swing.JLabel();
        lblDisponible1 = new javax.swing.JLabel();
        libro2Panel = new javax.swing.JPanel();
        lblTitulo2 = new javax.swing.JLabel();
        lblAutor2 = new javax.swing.JLabel();
        lblGenero2 = new javax.swing.JLabel();
        lblDisponible2 = new javax.swing.JLabel();
        libro6Panel = new javax.swing.JPanel();
        lblTitulo6 = new javax.swing.JLabel();
        lblAutor6 = new javax.swing.JLabel();
        lblGenero6 = new javax.swing.JLabel();
        lblDisponible6 = new javax.swing.JLabel();
        libro3Panel = new javax.swing.JPanel();
        lblTitulo3 = new javax.swing.JLabel();
        lblAutor3 = new javax.swing.JLabel();
        lblGenero3 = new javax.swing.JLabel();
        lblDisponible3 = new javax.swing.JLabel();
        libro4Panel = new javax.swing.JPanel();
        lblTitulo4 = new javax.swing.JLabel();
        lblAutor4 = new javax.swing.JLabel();
        lblGenero4 = new javax.swing.JLabel();
        lblDisponible4 = new javax.swing.JLabel();
        libro5Panel = new javax.swing.JPanel();
        lblTitulo5 = new javax.swing.JLabel();
        lblAutor5 = new javax.swing.JLabel();
        lblGenero5 = new javax.swing.JLabel();
        lblDisponible5 = new javax.swing.JLabel();
        btnReservar1 = new javax.swing.JButton();
        btnReservar2 = new javax.swing.JButton();
        btnReservar6 = new javax.swing.JButton();
        btnReservar3 = new javax.swing.JButton();
        btnReservar4 = new javax.swing.JButton();
        btnReservar5 = new javax.swing.JButton();
        lblNombreEstudiante = new javax.swing.JLabel();
        btnGenerarPdf = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("CONSULTA DE CATÁLOGO");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Buscar:");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        libro1Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo1.setText("jLabel3");

        lblAutor1.setText("jLabel4");

        lblGenero1.setText("jLabel5");

        lblDisponible1.setText("jLabel6");

        javax.swing.GroupLayout libro1PanelLayout = new javax.swing.GroupLayout(libro1Panel);
        libro1Panel.setLayout(libro1PanelLayout);
        libro1PanelLayout.setHorizontalGroup(
            libro1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libro1PanelLayout.createSequentialGroup()
                .addGroup(libro1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libro1PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDisponible1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libro1PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(libro1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(libro1PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblGenero1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        libro1PanelLayout.setVerticalGroup(
            libro1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libro1PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo1)
                .addGap(18, 18, 18)
                .addComponent(lblAutor1)
                .addGap(18, 18, 18)
                .addComponent(lblGenero1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDisponible1)
                .addGap(25, 25, 25))
        );

        libro2Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo2.setText("jLabel3");

        lblAutor2.setText("jLabel4");

        lblGenero2.setText("jLabel5");

        lblDisponible2.setText("jLabel6");

        javax.swing.GroupLayout libro2PanelLayout = new javax.swing.GroupLayout(libro2Panel);
        libro2Panel.setLayout(libro2PanelLayout);
        libro2PanelLayout.setHorizontalGroup(
            libro2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libro2PanelLayout.createSequentialGroup()
                .addGroup(libro2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libro2PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDisponible2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libro2PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(libro2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(libro2PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblGenero2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        libro2PanelLayout.setVerticalGroup(
            libro2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libro2PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo2)
                .addGap(18, 18, 18)
                .addComponent(lblAutor2)
                .addGap(18, 18, 18)
                .addComponent(lblGenero2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblDisponible2)
                .addGap(25, 25, 25))
        );

        libro6Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo6.setText("jLabel3");

        lblAutor6.setText("jLabel4");

        lblGenero6.setText("jLabel5");

        lblDisponible6.setText("jLabel6");

        javax.swing.GroupLayout libro6PanelLayout = new javax.swing.GroupLayout(libro6Panel);
        libro6Panel.setLayout(libro6PanelLayout);
        libro6PanelLayout.setHorizontalGroup(
            libro6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libro6PanelLayout.createSequentialGroup()
                .addGroup(libro6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libro6PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDisponible6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libro6PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(libro6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutor6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(libro6PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblGenero6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        libro6PanelLayout.setVerticalGroup(
            libro6PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libro6PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo6)
                .addGap(18, 18, 18)
                .addComponent(lblAutor6)
                .addGap(18, 18, 18)
                .addComponent(lblGenero6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblDisponible6)
                .addGap(25, 25, 25))
        );

        libro3Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo3.setText("jLabel3");

        lblAutor3.setText("jLabel4");

        lblGenero3.setText("jLabel5");

        lblDisponible3.setText("jLabel6");

        javax.swing.GroupLayout libro3PanelLayout = new javax.swing.GroupLayout(libro3Panel);
        libro3Panel.setLayout(libro3PanelLayout);
        libro3PanelLayout.setHorizontalGroup(
            libro3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libro3PanelLayout.createSequentialGroup()
                .addGroup(libro3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libro3PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDisponible3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libro3PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(libro3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutor3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(libro3PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblGenero3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        libro3PanelLayout.setVerticalGroup(
            libro3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libro3PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo3)
                .addGap(18, 18, 18)
                .addComponent(lblAutor3)
                .addGap(18, 18, 18)
                .addComponent(lblGenero3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblDisponible3)
                .addGap(25, 25, 25))
        );

        libro4Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo4.setText("jLabel3");

        lblAutor4.setText("jLabel4");

        lblGenero4.setText("jLabel5");

        lblDisponible4.setText("jLabel6");

        javax.swing.GroupLayout libro4PanelLayout = new javax.swing.GroupLayout(libro4Panel);
        libro4Panel.setLayout(libro4PanelLayout);
        libro4PanelLayout.setHorizontalGroup(
            libro4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libro4PanelLayout.createSequentialGroup()
                .addGroup(libro4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libro4PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDisponible4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libro4PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(libro4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutor4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(libro4PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblGenero4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        libro4PanelLayout.setVerticalGroup(
            libro4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libro4PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo4)
                .addGap(18, 18, 18)
                .addComponent(lblAutor4)
                .addGap(18, 18, 18)
                .addComponent(lblGenero4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblDisponible4)
                .addGap(25, 25, 25))
        );

        libro5Panel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTitulo5.setText("jLabel3");

        lblAutor5.setText("jLabel4");

        lblGenero5.setText("jLabel5");

        lblDisponible5.setText("jLabel6");

        javax.swing.GroupLayout libro5PanelLayout = new javax.swing.GroupLayout(libro5Panel);
        libro5Panel.setLayout(libro5PanelLayout);
        libro5PanelLayout.setHorizontalGroup(
            libro5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, libro5PanelLayout.createSequentialGroup()
                .addGroup(libro5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(libro5PanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDisponible5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, libro5PanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(libro5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAutor5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTitulo5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 20, 20))
            .addGroup(libro5PanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblGenero5, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        libro5PanelLayout.setVerticalGroup(
            libro5PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(libro5PanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTitulo5)
                .addGap(18, 18, 18)
                .addComponent(lblAutor5)
                .addGap(18, 18, 18)
                .addComponent(lblGenero5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblDisponible5)
                .addGap(25, 25, 25))
        );

        btnReservar1.setText("jButton1");

        btnReservar2.setText("jButton2");

        btnReservar6.setText("jButton3");
        btnReservar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservar6ActionPerformed(evt);
            }
        });

        btnReservar3.setText("jButton4");

        btnReservar4.setText("jButton5");

        btnReservar5.setText("jButton6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnReservar5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReservar6)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnReservar3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReservar4)
                .addGap(148, 148, 148))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(libro1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                                .addComponent(libro2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(libro5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(libro6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(libro3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(libro4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnReservar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReservar2)
                        .addGap(147, 147, 147))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(libro2Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(libro1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar1)
                    .addComponent(btnReservar2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(libro4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libro3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReservar4)
                    .addComponent(btnReservar3))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(libro5Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(libro6Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReservar5)
                    .addComponent(btnReservar6))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        lblNombreEstudiante.setText("jLabel3");

        btnGenerarPdf.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombreEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_buscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnGenerarPdf)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNombreEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jtxt_buscarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGenerarPdf, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservar6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReservar6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGenerarPdf;
    public javax.swing.JButton btnReservar1;
    public javax.swing.JButton btnReservar2;
    public javax.swing.JButton btnReservar3;
    public javax.swing.JButton btnReservar4;
    public javax.swing.JButton btnReservar5;
    public javax.swing.JButton btnReservar6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTextField jtxt_buscarLibros;
    public javax.swing.JLabel lblAutor1;
    public javax.swing.JLabel lblAutor2;
    public javax.swing.JLabel lblAutor3;
    public javax.swing.JLabel lblAutor4;
    public javax.swing.JLabel lblAutor5;
    public javax.swing.JLabel lblAutor6;
    public javax.swing.JLabel lblDisponible1;
    public javax.swing.JLabel lblDisponible2;
    public javax.swing.JLabel lblDisponible3;
    public javax.swing.JLabel lblDisponible4;
    public javax.swing.JLabel lblDisponible5;
    public javax.swing.JLabel lblDisponible6;
    public javax.swing.JLabel lblGenero1;
    public javax.swing.JLabel lblGenero2;
    public javax.swing.JLabel lblGenero3;
    public javax.swing.JLabel lblGenero4;
    public javax.swing.JLabel lblGenero5;
    public javax.swing.JLabel lblGenero6;
    public javax.swing.JLabel lblNombreEstudiante;
    public javax.swing.JLabel lblTitulo1;
    public javax.swing.JLabel lblTitulo2;
    public javax.swing.JLabel lblTitulo3;
    public javax.swing.JLabel lblTitulo4;
    public javax.swing.JLabel lblTitulo5;
    public javax.swing.JLabel lblTitulo6;
    public javax.swing.JPanel libro1Panel;
    public javax.swing.JPanel libro2Panel;
    public javax.swing.JPanel libro3Panel;
    public javax.swing.JPanel libro4Panel;
    public javax.swing.JPanel libro5Panel;
    public javax.swing.JPanel libro6Panel;
    // End of variables declaration//GEN-END:variables
}
