/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author amagu
 */
public class GestionBibliotecarios extends javax.swing.JPanel {

    /**
     * Creates new form GestionBibliotecarios
     */
    public GestionBibliotecarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_buscarBibliotecario = new javax.swing.JTextField();
        jbtn_buscarBibliotecario = new javax.swing.JButton();
        jbtn_agregarBiblioteario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtb_Bibliotecarios = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, 500, 10));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel1.setText("GESTION DE BIBLIOTECARIOS");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 13, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Usuario: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));
        add(jtxt_buscarBibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 180, 30));

        jbtn_buscarBibliotecario.setText("Buscar");
        add(jbtn_buscarBibliotecario, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, 30));

        jbtn_agregarBiblioteario.setText("Agregar");
        jbtn_agregarBiblioteario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarBibliotearioActionPerformed(evt);
            }
        });
        add(jbtn_agregarBiblioteario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, 30));

        jtb_Bibliotecarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtb_Bibliotecarios);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 500, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_agregarBibliotearioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarBibliotearioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_agregarBibliotearioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JSeparator jSeparator1;
    public javax.swing.JButton jbtn_agregarBiblioteario;
    public javax.swing.JButton jbtn_buscarBibliotecario;
    public javax.swing.JTable jtb_Bibliotecarios;
    public javax.swing.JTextField jtxt_buscarBibliotecario;
    // End of variables declaration//GEN-END:variables
}
