/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author amagu
 */
public class VistaContenedor extends javax.swing.JFrame {

    /**
     * Creates new form VistaGestionCatalogos
     */
    public VistaContenedor() {
        initComponents();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jlb_Roles = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jpBtn1 = new javax.swing.JPanel();
        jbtn_1 = new javax.swing.JButton();
        jpBtn2 = new javax.swing.JPanel();
        jbtn_2 = new javax.swing.JButton();
        jpBtn3 = new javax.swing.JPanel();
        jbtn_3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlb_Roles.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jlb_Roles.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jlb_Roles, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 140, 24));

        jButton1.setBackground(new java.awt.Color(231, 76, 60));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cerrar Sesión");
        jButton1.setBorder(null);
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 390, 140, 34));

        jpBtn1.setLayout(new java.awt.BorderLayout());

        jbtn_1.setBackground(new java.awt.Color(41, 128, 185));
        jbtn_1.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_1.setBorder(null);
        jpBtn1.add(jbtn_1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jpBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 30));

        jpBtn2.setLayout(new java.awt.BorderLayout());

        jbtn_2.setBackground(new java.awt.Color(41, 128, 185));
        jbtn_2.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_2.setBorder(null);
        jbtn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_2ActionPerformed(evt);
            }
        });
        jpBtn2.add(jbtn_2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jpBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 130, 30));

        jpBtn3.setLayout(new java.awt.BorderLayout());

        jbtn_3.setBackground(new java.awt.Color(41, 128, 185));
        jbtn_3.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_3.setBorder(null);
        jpBtn3.add(jbtn_3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jpBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 130, 30));

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(567, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("SISTEMA RESERVA DE LIBROS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 350, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaContenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaContenedor().setVisible(true);
                VistaContenedor contenedor = new VistaContenedor();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JButton jbtn_1;
    public javax.swing.JButton jbtn_2;
    public javax.swing.JButton jbtn_3;
    public javax.swing.JLabel jlb_Roles;
    public javax.swing.JPanel jpBtn1;
    public javax.swing.JPanel jpBtn2;
    public javax.swing.JPanel jpBtn3;
    // End of variables declaration//GEN-END:variables
}
